[package]
name = "learn-vulkan"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [ "Win32_System_LibraryLoader", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi"] }

[build-dependencies]
bindgen = "0.72.1"