use crate::vulkan::bindings::{
    VK_EXT_METAL_SURFACE_EXTENSION_NAME, VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR,
    VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME, VK_KHR_SURFACE_EXTENSION_NAME,
};

pub const INSTANCE_EXTENSIONS: [&[u8]; 3] = [
    VK_KHR_SURFACE_EXTENSION_NAME,
    VK_EXT_METAL_SURFACE_EXTENSION_NAME,
    VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME,
];

pub const INSTANCE_CREATION_FLAGS: u32 = VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR;
