use crate::vulkan::bindings::{VK_KHR_SURFACE_EXTENSION_NAME, VK_KHR_WIN32_SURFACE_EXTENSION_NAME};

pub const INSTANCE_EXTENSIONS: [&[u8]; 2] = [
    VK_KHR_SURFACE_EXTENSION_NAME,
    VK_KHR_WIN32_SURFACE_EXTENSION_NAME,
];

pub const INSTANCE_CREATION_FLAGS: u32 = 0;
